const calc = (num) => `calc(${num} * 16px)`;

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.stories.{js,jsx,ts,tsx}",
    "./public/popup.html",
    "./.storybook/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    screens: {
      xs: "1024px",
      sm: "1440px",
      md: "1920px",
      lg: "2560px",
    },
    container: {
      center: true,
      padding: calc(2),
    },
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        tertiary: {
          DEFAULT: "#F5F5F5",
        },
        brand: {
          DEFAULT: "#4E1DF5",
          solid: "#3D11C4",
        },
        disabled: {
          DEFAULT: "#F5F5F5",
          foreground: "#A3A3A3",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
          hover: "var(--destructive-hover)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        toast: {
          DEFAULT: "var(--toast-background)",
          foreground: "var(--toast-foreground)",
          destructive: "var(--toast-destructive)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        lavender: {
          500: "#594DF2",
        },
      },
      textColor: {
        primary: "#141414",
        secondary: "#424242",
        tertiary: "#525252",
        buttonTertiary: "#1F1F1F",
        label: "#1F1F1F",
        placeholder: "#737373",
        btnLink: "#4A15EC",
        keystroke: "#989898",
        warning: "#DC6803",
        warningSecondary: "#F79009",
        error: "#F04438",
      },
      backgroundColor: {
        buttonPrimary: "#141414",
        buttonDisabled: "#eaeaea",
        fgForeground: "#424242",
        fgSecondaryHover: "#292929",
        primarySolid: "#0F0F0F",
        toolbar: "#1F1F1F",
        buttonSecondary: "#424242",
        buttonTertiary: "#525252",
        switchThumb: "#737373",
        warningPrimary: "#FFFAEB",
        warningSecondary: "#F79009",
        errorPrimary: "#FEF3F2",
      },
      fontSize: {
        xxs: [calc(0.625), calc(1)],
        xs: [calc(0.75), calc(1.125)],
        sm: [calc(0.875), calc(1.25)],
        base: [calc(1), calc(1.5)],
        lg: [calc(1.125), calc(1.75)],
        xl: [calc(1.25), calc(1.875)],
        "2xl": [calc(1.5), calc(2)],
        "3xl": [calc(2), calc(2.5)],
      },
      borderColor: {
        primary: "#D6D6D6",
        secondary: "#292929",
        medium: "#E4E4E4",
        disabled: "#E5E5E5",
        toolbar: "#000",
        fgSecondaryHover: "#292929",
        fgSecondary: "#424242",
        fgQuaternary: "#737373",
        tertiary: "#F5F5F5",
      },
      borderRadius: {
        none: calc(0),
        xxs: calc(0.125),
        xs: calc(0.25),
        sm: calc(0.375),
        md: calc(0.5),
        lg: calc(0.625),
        xl: calc(0.75),
        "2xl": calc(1),
        "3xl": calc(1.25),
        "4xl": calc(1.5),
        full: calc(62.5),
      },
      keyframes: {
        tooltipFadeIn: {
          "0%": { transform: "translateY(-25px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        tooltipFadeOut: {
          "0%": { transform: "translateY(0)", opacity: "1" },
          "100%": { transform: "translateY(-25px)", opacity: "0" },
        },
        loading: {
          "0%": {
            strokeDasharray: "1, 215",
            strokeDashoffset: "0",
          },
          "50%": {
            strokeDasharray: "107.5, 107.5",
            strokeDashoffset: "-107.5",
          },
          "100%": {
            strokeDasharray: "1, 215",
            strokeDashoffset: "-215",
          },
        },
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        loading: "loading 1s linear infinite",
        tooltipFadeIn: "tooltipFadeIn 300ms ease-in forwards",
        tooltipFadeOut: "tooltipFadeOut 300ms ease-out forwards",
      },
      boxShadow: {
        "ring-gray-shadow-xs":
          "0px 1px 2px 0px rgba(16, 24, 40, 0.05), 0px 0px 0px 4px rgba(152, 162, 179, 0.14)",
        "ring-error-shadow-xs":
          "0px 1px 2px 0px rgba(16, 24, 40, 0.05), 0px 0px 0px 4px rgba(240, 68, 56, 0.24)",
      },
      variants: {
        extend: {
          fill: ["group-hover"],
        },
      },
      lineHeight: {
        0: calc(0),
        0.5: calc(0.125),
        1: calc(0.25),
        1.5: calc(0.375),
        2: calc(0.5),
        2.5: calc(0.625),
        3: calc(0.75),
        3.5: calc(0.875),
        4.5: calc(1.125),
        5: calc(1.25),
        6: calc(1.5),
        7: calc(1.75),
        8: calc(2),
      },
      spacing: {
        0: calc(0),
        0.5: calc(0.125),
        1: calc(0.25),
        1.25: calc(0.3125),
        1.5: calc(0.375),
        2: calc(0.5),
        2.5: calc(0.625),
        3: calc(0.75),
        3.5: calc(0.875),
        4: calc(1),
        4.5: calc(1.125),
        5: calc(1.25),
        6: calc(1.5),
        7: calc(1.75),
        8: calc(2),
        9: calc(2.25),
        10: calc(2.5),
        12: calc(3),
        14: calc(3.5),
        16: calc(4),
        18: calc(4.5),
        20: calc(5),
        24: calc(6),
        28: calc(7),
        32: calc(8),
      },
      height: {
        0: calc(0),
        0.5: calc(0.125),
        1: calc(0.25),
        1.5: calc(0.375),
        2: calc(0.5),
        2.5: calc(0.625),
        3: calc(0.75),
        3.5: calc(0.875),
        4: calc(1),
        4.5: calc(1.125),
        5: calc(1.25),
        6: calc(1.5),
        7: calc(1.75),
        8: calc(2),
        9: calc(2.25),
        10: calc(2.5),
        12: calc(3),
        14: calc(3.5),
        16: calc(4),
        18: calc(4.5),
        20: calc(5),
        40: calc(10),
        60: calc(15),
        72: calc(18),
        80: calc(20),
      },
      width: {
        0: calc(0),
        0.5: calc(0.125),
        1: calc(0.25),
        1.5: calc(0.375),
        2: calc(0.5),
        2.5: calc(0.625),
        3: calc(0.75),
        3.5: calc(0.875),
        4: calc(1),
        4.5: calc(1.125),
        5: calc(1.25),
        6: calc(1.5),
        7: calc(1.75),
        8: calc(2),
        9: calc(2.25),
        10: calc(2.5),
        12: calc(3),
        14: calc(3.5),
        16: calc(4),
        18: calc(4.5),
        20: calc(5),
        40: calc(10),
        60: calc(15),
        72: calc(18),
        80: calc(20),
      },
      inset: {
        0: calc(0),
        0.5: calc(0.125),
        1: calc(0.25),
        1.5: calc(0.375),
        2: calc(0.5),
        2.5: calc(0.625),
        3: calc(0.75),
        3.5: calc(0.875),
        4: calc(1),
        4.5: calc(1.125),
        5: calc(1.25),
        6: calc(1.5),
        7: calc(1.75),
        8: calc(2),
      },
    },
  },
};
